#!/usr/bin/env node
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadLearningArtifacts } from './validate-artifacts.mjs';

const REPOSITORY_ROOT = resolve(fileURLToPath(new URL('../..', import.meta.url)));
const INDEX_PATH = resolve(REPOSITORY_ROOT, 'docs/agent-learning/index.md');

export function generateArtifactIndex(records) {
  const sorted = [...records].sort((left, right) => left.artifact.id.localeCompare(right.artifact.id));
  const counts = new Map();
  for (const { artifact } of sorted) counts.set(artifact.status, (counts.get(artifact.status) || 0) + 1);
  const rows = sorted.map(({ artifact }) => [
    `[${artifact.id}](artifacts/${artifact.id}.yml)`,
    artifact.severity,
    artifact.status,
    String(artifact.recurrenceCount),
    artifact.prevention.map((item) => `\`${item.path}\` (${item.kind})`).join('<br>'),
  ]);
  const lines = [
    '# Learning invariants',
    '',
    '<!-- Generated by scripts/agent-learning/generate-index.mjs. Do not edit manually. -->',
    '',
    `Records: ${sorted.length}. Active: ${counts.get('active') || 0}; verified: ${counts.get('verified') || 0}; superseded: ${counts.get('superseded') || 0}.`,
    '',
    ...renderTable(['Invariant', 'Severity', 'Status', 'Recurrence', 'Prevention'], rows, new Set([3])),
  ];
  return `${lines.join('\n')}\n`;
}

function renderTable(headers, rows, rightAligned) {
  const widths = headers.map((header, index) =>
    Math.max(header.length, 3, ...rows.map((row) => String(row[index]).length)),
  );
  const renderRow = (row) =>
    `| ${row
      .map((value, index) =>
        rightAligned.has(index) ? String(value).padStart(widths[index]) : String(value).padEnd(widths[index]),
      )
      .join(' | ')} |`;
  const separator = widths.map((width, index) =>
    rightAligned.has(index) ? `${'-'.repeat(width - 1)}:` : '-'.repeat(width),
  );
  return [renderRow(headers), renderRow(separator), ...rows.map(renderRow)];
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const result = loadLearningArtifacts();
  if (result.errors.length > 0) {
    console.error(`Learning artifact validation failed:\n- ${result.errors.join('\n- ')}`);
    process.exit(1);
  }
  const generated = generateArtifactIndex(result.records);
  if (process.argv.includes('--check')) {
    const current = readFileSync(INDEX_PATH, 'utf8');
    if (current !== generated) {
      console.error('docs/agent-learning/index.md is stale; run npm run agent:learning:index.');
      process.exit(1);
    }
    console.log('Learning artifact index is current.');
  } else {
    writeFileSync(INDEX_PATH, generated);
    console.log('Updated docs/agent-learning/index.md.');
  }
}
