import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  artifactStatusCounts,
  ARTIFACT_STATES,
  REPOSITORY_ROOT,
  validateArtifactRepository,
} from './validate-artifacts.mjs';

export const DEFAULT_INDEX_PATH = resolve(REPOSITORY_ROOT, 'docs/agent-learning/index.md');

export function renderArtifactIndex(entries) {
  const sorted = [...entries].sort((left, right) => left.artifact.id.localeCompare(right.artifact.id));
  const counts = artifactStatusCounts(sorted);
  const statusSummary = ARTIFACT_STATES.map((status) => `${status}: ${counts[status]}`).join('; ');
  const lines = [
    '# Agent learning artifact index',
    '',
    '<!-- Generated by scripts/agent-learning/generate-index.mjs. Do not edit manually. -->',
    '',
    `Artifacts: ${sorted.length}. ${statusSummary}.`,
  ];
  for (const { artifact } of sorted) {
    const references = artifact.source.references.map((reference) => reference.locator).join(', ');
    lines.push('', `## [${artifact.id}](artifacts/${artifact.id}.yml)`, '');
    lines.push(`- Title: ${artifact.title}`);
    lines.push(`- Source: ${artifact.source.type} — ${references}`);
    lines.push(`- Disposition: ${artifact.disposition.primary}`);
    lines.push(`- Status: ${artifact.status}`);
    lines.push('- Durable artifacts:');
    if (artifact.artifacts.length === 0) lines.push('  - None (exception disposition)');
    else artifact.artifacts.forEach((entry) => lines.push(`  - \`${entry.path}\` (${entry.kind})`));
  }
  lines.push('');
  return lines.join('\n');
}

export function generateArtifactIndex(options = {}) {
  const validation = validateArtifactRepository(options);
  if (validation.errors.length > 0) {
    throw new Error(`Cannot generate an index from invalid artifacts:\n- ${validation.errors.join('\n- ')}`);
  }
  return renderArtifactIndex(validation.artifacts);
}

function runCli() {
  const args = process.argv.slice(2);
  if (args.some((arg) => arg !== '--check')) {
    throw new Error(`Unsupported arguments: ${args.filter((arg) => arg !== '--check').join(' ')}`);
  }
  const rendered = generateArtifactIndex();
  if (args.includes('--check')) {
    let existing;
    try {
      existing = readFileSync(DEFAULT_INDEX_PATH, 'utf8');
    } catch {
      throw new Error('Generated learning artifact index is missing. Run npm run agent:learning:index.');
    }
    if (existing !== rendered) {
      throw new Error('Generated learning artifact index is stale. Run npm run agent:learning:index.');
    }
    console.log('Learning artifact index is reproducible and current.');
    return;
  }
  writeFileSync(DEFAULT_INDEX_PATH, rendered);
  console.log(`Wrote ${DEFAULT_INDEX_PATH}.`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try {
    runCli();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
