import { getCategoryIndex } from './categoryStore.js';
import { WlhClient, WlhFetchError, type FetchLike } from './client.js';
import { normalizeSearchRequest, WlhInputError } from './input.js';
import { htmlToText, normalizeText } from './normalize.js';

const conditionMap: Record<string,string>={new:'22',like_new:'2546',used:'23',defect:'24'};
const deliveryMap: Record<string,string>={pickup:'2536',shipping:'2537'};

export class WlhNotFoundError extends Error {}
export class WlhService { private client: WlhClient; constructor(fetchImpl?:FetchLike){ this.client=new WlhClient(fetchImpl); }
  async topCategories(){ return (await getCategoryIndex()).top; }
  async category(id:string){ const c=(await getCategoryIndex()).byId.get(id); if(!c) throw new WlhNotFoundError('not found'); return c; }
  async children(id:string){ const idx=await getCategoryIndex(); if(!idx.byId.has(id)&&id!=='0') throw new WlhNotFoundError('not found'); return idx.childrenByParentId.get(id)??[]; }
  async search(body:unknown){ const req=normalizeSearchRequest(body); const cat=await this.category(req.categoryId); const base = cat.url || cat.path || '/'; const url = new URL(base, (await import('./config.js')).readWlhConfig().baseUrl); url.search=''; if(req.keyword) url.searchParams.set('keyword',req.keyword); url.searchParams.set('rows',String(req.rows)); url.searchParams.set('page',String(req.page)); if(req.areaId) url.searchParams.set('areaId',req.areaId); if(req.priceFrom!=null) url.searchParams.set('PRICE_FROM',String(req.priceFrom)); if(req.priceTo!=null) url.searchParams.set('PRICE_TO',String(req.priceTo)); if(req.paylivery) url.searchParams.set('paylivery','true'); if(req.condition) url.searchParams.append('treeAttributes',conditionMap[req.condition]); for(const d of req.delivery??[]) url.searchParams.append('treeAttributes',deliveryMap[d]); const res=await this.client.fetchNextData(url.toString()); const rows=(res.data?.props?.pageProps?.searchResult?.advertSummaryList?.advertSummary??[]).map((x:any)=>({id:String(x.id??x.advertId??''),title:String(x.description??x.title??''),priceAmount:Number(x.price?.amount??NaN)||null,priceDisplay:String(x.price?.description??''),location:String(x?.address?.city??''),postcode:x?.address?.postcode,state:x?.address?.state,publishedAt:x?.published,changedAt:x?.modified,paylivery:typeof x?.areP2POptionsEnabled==='boolean'?x.areP2POptionsEnabled:null,sellerId:x?.seller?.id?String(x.seller.id):undefined,url:String(x?.seoUrl??x?.url??''),imageCount:Number(x?.imageUrls?.length??0),thumbnailUrl:x?.imageUrls?.[0],_body:String(x?.text??'')})); const terms=(req.requiredTerms??[]).map(normalizeText).filter(Boolean); const filtered=terms.length?rows.filter((r:any)=>{const hay=normalizeText(`${r.title} ${r._body}`); return terms.every((t)=>hay.includes(t));}):rows; return {source:'wlh',fetchedAt:new Date().toISOString(),sourceUrl:res.url,rowsFound:res.data?.props?.pageProps?.searchResult?.numFound??null,rowsReturned:rows.length,filteredRowsReturned:filtered.length,category:cat,results:filtered.map(({_body,...x}:any)=>x)}; }
  async offer(adId:string){ const d=(await this.client.fetchNextData(`/iad/kaufen-und-verkaufen/d/${adId}`)).data?.props?.pageProps?.advertDetails; const p2p=d?.p2ppOptions; const paylivery=Boolean((p2p?.deliveryOptions?.length??0)||(p2p?.paymentOptions?.length??0)); const images=(d?.images??[]).map((i:any)=>({id:String(i?.id??''),url:i?.url||i?.baseUrl||i?.smallUrl})); return {id:String(d?.id??adId),title:String(d?.title??''),description:htmlToText(String(d?.description??d?.body??'')),priceAmount:Number(d?.price?.amount??NaN)||null,priceDisplay:String(d?.price?.description??''),location:String(d?.address?.city??''),postcode:d?.address?.postcode,state:d?.address?.state,publishedAt:d?.published,changedAt:d?.modified,status:d?.status,seller:d?.seller?{id:String(d.seller.id??''),name:String(d.seller.name??'')}:undefined,paylivery,deliveryOptions:d?.p2ppOptions?.deliveryOptions??[],images}; }
  async offerImages(adId:string){ return {source:'wlh',adId,images:(await this.offer(adId)).images}; }
}
export function mapWlhError(error:unknown){ if(error instanceof WlhInputError) return {status:400,message:error.message}; if(error instanceof WlhNotFoundError) return {status:404,message:error.message}; if(error instanceof WlhFetchError) return {status:error.status,message:error.message}; return {status:502,message:'wlh failure'}; }
