import { BringClient, BringUpstreamError, type BringFetch } from './client.js';
import { readBringConfig } from './config.js';
import { AzureBlobBringSessionStore, type BringSessionStore, type SafeWarning } from './sessionStore.js';
import type { BringConfig, BringItem, BringItemInput, BringList, BringListSummary, BringSession } from './types.js';

export class BringInputError extends Error { constructor(message: string, readonly field?: string) { super(message); } }
export class BringNotFoundError extends Error {}
const uuidPattern = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export class BringService {
  private readonly config: BringConfig; private readonly client: BringClient; private readonly store: BringSessionStore | null;
  private session: BringSession | null = null; private authenticationPromise: Promise<BringSession> | null = null; private durableLoaded = false;
  private readonly warn: SafeWarning;
  constructor(deps: { config?: BringConfig; fetchImpl?: BringFetch; sessionStore?: BringSessionStore | null; now?: () => Date; warn?: SafeWarning } = {}) {
    this.config = deps.config ?? readBringConfig(); const now = deps.now ?? (() => new Date()); this.now = now; this.client = new BringClient(this.config, deps.fetchImpl, now);
    this.warn = deps.warn ?? (() => {}); this.store = deps.sessionStore !== undefined ? deps.sessionStore : this.config.sessionCacheEnabled ? new AzureBlobBringSessionStore(this.config, this.warn) : null;
  }
  private readonly now: () => Date;
  async listLists(): Promise<{ source: 'bring'; lists: BringListSummary[] }> { const raw: any = await this.authorized((s) => this.client.getLists(s)); const rows = Array.isArray(raw?.lists) ? raw.lists : Array.isArray(raw) ? raw : null; if (!rows) throw new BringUpstreamError('Bring list response shape changed.', 502, 'version_skew'); const session = await this.authenticate(); const lists = rows.map((x: any) => ({ uuid: String(x.listUuid ?? x['uuid'] ?? ''), name: String(x['name'] ?? x.listName ?? ''), ...(x.theme ? { theme: String(x.theme) } : {}), isDefault: String(x.listUuid ?? x['uuid'] ?? '') === (this.config.defaultListUuid ?? session.defaultListUuid) })).filter((x: BringListSummary) => x['uuid'] && x['name']); return { source: 'bring', lists }; }
  async getList(listUuid?: string): Promise<BringList> { const id = await this.resolveListUuid(listUuid); const raw: any = await this.authorized((s) => this.client.getList(s, id)); const active = Array.isArray(raw?.purchase) ? raw.purchase : Array.isArray(raw?.items) ? raw.items : []; const completed = Array.isArray(raw?.recently) ? raw.recently : Array.isArray(raw?.completed) ? raw.completed : []; return { uuid: id, ...(raw?.name ? { name: String(raw.name) } : {}), items: [...active.map((x: any) => normalizeItem(x, 'active')), ...completed.map((x: any) => normalizeItem(x, 'completed'))] }; }
  async addItems(listUuid: string | undefined, items: BringItemInput[]) { return this.changeItems('add', listUuid, items); }
  async completeItems(listUuid: string | undefined, items: BringItemInput[]) { return this.changeItems('complete', listUuid, items); }
  private async changeItems(operation: 'add' | 'complete', listUuid: string | undefined, input: BringItemInput[]) { const items = validateItems(input); const id = await this.resolveListUuid(listUuid); await this.authorized((s) => this.client.updateItems(s, id, items, operation)); return { source: 'bring' as const, listUuid: id, operation, itemCount: items.length, items }; }
  private async resolveListUuid(value?: string): Promise<string> { if (value !== undefined) { if (!uuidPattern.test(value)) throw new BringInputError('listUuid must be a valid UUID.', 'listUuid'); return value; } const session = await this.authenticate(); if (this.config.defaultListUuid) return this.config.defaultListUuid; if (session.defaultListUuid) return session.defaultListUuid; const lists = await this.listLists(); if (!lists.lists[0]) throw new BringNotFoundError('No Bring list is available.'); session.defaultListUuid = lists.lists[0].uuid; return lists.lists[0].uuid; }
  private async authorized<T>(fn: (s: BringSession) => Promise<T>): Promise<T> { let session = await this.authenticate(); try { return await fn(session); } catch (e) { if (!(e instanceof BringUpstreamError) || e.kind !== 'authentication') throw e; this.session = null; this.authenticationPromise = null; session = await this.authenticate(true); return fn(session); } }
  private authenticate(forceLogin = false): Promise<BringSession> { if (!forceLogin && this.session && this.valid(this.session)) return Promise.resolve(this.session); if (this.authenticationPromise) return this.authenticationPromise; this.authenticationPromise = this.authenticateInner(forceLogin).finally(() => { this.authenticationPromise = null; }); return this.authenticationPromise; }
  private async authenticateInner(forceLogin: boolean): Promise<BringSession> { if (!forceLogin && !this.durableLoaded) { this.durableLoaded = true; try { this.session = await this.store?.load() ?? null; } catch { this.warn('Bring session cache read failed; authentication will continue without it.'); this.session = null; } } if (!forceLogin && this.session && this.valid(this.session)) return this.session; if (!forceLogin && this.session?.refreshToken) { try { return await this.persist(await this.client.refresh(this.session.refreshToken, this.session)); } catch (e) { if (!(e instanceof BringUpstreamError) || e.kind !== 'authentication') throw e; try { await this.store?.clear(); } catch { this.warn('Bring session cache clear failed.'); } this.session = null; } } return this.persist(await this.client.login()); }
  private valid(s: BringSession) { return Date.parse(s.accessTokenExpiresAt) - this.now().getTime() > 60_000; }
  private async persist(s: BringSession) { this.session = s; try { await this.store?.save(s); } catch { this.warn('Bring session cache write failed; the successful upstream operation is unaffected.'); } return s; }
}
function normalizeItem(x: any, status: BringItem['status']): BringItem { return { ...(x['uuid'] || x.itemUuid ? { uuid: String(x['uuid'] ?? x.itemUuid) } : {}), name: String(x['name'] ?? x.itemId ?? ''), ...(x['specification'] ? { specification: String(x['specification']) } : {}), status }; }
export function validateItems(value: unknown): BringItemInput[] { if (!Array.isArray(value) || value.length < 1 || value.length > 50) throw new BringInputError('items must contain between 1 and 50 entries.', 'items'); return value.map((raw, index) => { if (!raw || typeof raw !== 'object' || Array.isArray(raw)) throw new BringInputError(`items[${index}] must be an object.`, 'items'); const x = raw as Record<string, unknown>; const unknown = Object.keys(x).filter((k) => !['name', 'specification', 'uuid'].includes(k)); if (unknown.length) throw new BringInputError(`items[${index}] contains unknown fields.`, 'items'); if (typeof x['name'] !== 'string' || !x['name'].trim() || x['name'].length > 200) throw new BringInputError(`items[${index}].name must contain 1-200 characters.`, 'items'); if (x['specification'] !== undefined && (typeof x['specification'] !== 'string' || x['specification'].length > 500)) throw new BringInputError(`items[${index}].specification must not exceed 500 characters.`, 'items'); if (x['uuid'] !== undefined && (typeof x['uuid'] !== 'string' || !uuidPattern.test(x['uuid']))) throw new BringInputError(`items[${index}].uuid must be a valid UUID.`, 'items'); return { name: x['name'], ...(x['specification'] !== undefined ? { specification: x['specification'] as string } : {}), ...(x['uuid'] !== undefined ? { uuid: x['uuid'] as string } : {}) }; }); }
